# Generated by Django 4.2.3 on 2023-07-27 14:19

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "elxr_account_detail",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeTestDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("deadline", models.DateTimeField()),
                ("passing_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_attempts", models.IntegerField()),
                ("recepients", models.TextField()),
                ("questions", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "elxr_knowledge_test_details",
            },
        ),
        migrations.CreateModel(
            name="UpdateDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("deadline", models.CharField(max_length=100)),
                ("recepients", models.TextField()),
                ("update_type", models.CharField(max_length=50)),
                ("update_source", models.CharField(max_length=50)),
                (
                    "update_message",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "elxr_update_details",
            },
        ),
        migrations.CreateModel(
            name="UserUpdateResponses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "ack_status",
                    models.CharField(
                        choices=[("P", "Pending"), ("C", "Completed")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("ack_comments", models.CharField(max_length=200)),
                (
                    "update_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.updatedetails",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "elxr_user_update_responses",
            },
        ),
        migrations.CreateModel(
            name="UserSentUpdatePkt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pkt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.knowledgetestdetails",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.updatedetails",
                    ),
                ),
            ],
            options={
                "db_table": "elxr_sent_update_pkt",
            },
        ),
        migrations.CreateModel(
            name="UserPktResponses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("user_answer", models.TextField()),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pass"), ("F", "Fail"), ("N", "NA")],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "pkt_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.knowledgetestdetails",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "elxr_pkt_responses",
            },
        ),
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "account_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.accountdetails",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "elxr_user_details",
            },
        ),
        migrations.CreateModel(
            name="QuestionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("TOF", "True Or False"),
                            ("MCQ", "Multiple Choice Question"),
                            ("MAQ", "Multiple Answer Question"),
                            ("SUB", "Subjective"),
                        ],
                        max_length=3,
                    ),
                ),
                ("mark", models.DecimalField(decimal_places=2, max_digits=5)),
                ("media_type", models.CharField(max_length=100, null=True)),
                ("media_url", models.CharField(max_length=200, null=True)),
                ("answer_options", models.TextField()),
                ("correct_answer", models.TextField()),
                ("tag", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "elxr_question_details",
            },
        ),
        migrations.AddField(
            model_name="knowledgetestdetails",
            name="update_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.updatedetails",
            ),
        ),
    ]
