# Generated by Django 4.2.3 on 2023-07-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_updatedetails_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiondetails",
            name="question",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="updatedetails",
            name="update_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
