# Generated by Django 4.2.3 on 2023-07-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_questiondetails_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersentupdatepkt",
            name="pkt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.knowledgetestdetails",
            ),
        ),
        migrations.AlterField(
            model_name="usersentupdatepkt",
            name="update",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.updatedetails",
            ),
        ),
    ]
