# Generated by Django 4.2.3 on 2023-07-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_usersentupdatepkt_pkt_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questiondetails",
            old_name="tag",
            new_name="question_tag",
        ),
    ]
